[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]

rmqtt = { version = "0.15.0-beta.5", features = ["ws", "tls"] }
tokio = { version = "1", features = ["full"] }
simple_logger = "5"
log = "0.4"